name: grocery_inventory_app
description: A simple Flutter app for capturing video and detecting food items.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  google_mlkit_object_detection: ^0.15.0
  google_mlkit_image_labeling: ^0.14.1   # <- bump to align with commons ^0.11.x

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
