name: grocery_inventory_app
description: A simple Flutter app for capturing video and detecting food items.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  google_mlkit_object_detection: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
