// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhGEHV6eqB0-IsSWicNB9QCQlzrHmGoY0',
    appId: '1:667875871369:web:f4a914d752df7d82dad458',
    messagingSenderId: '667875871369',
    projectId: 'groc-b18e4',
    authDomain: 'groc-b18e4.firebaseapp.com',
    storageBucket: 'groc-b18e4.firebasestorage.app',
    measurementId: 'G-2GL4EHPB59',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB4Bd7X2nuhmDJ4G5U4I7bsqQhQzvK-oM',
    appId: '1:667875871369:ios:b1ee4ca6e67620ebdad458',
    messagingSenderId: '667875871369',
    projectId: 'groc-b18e4',
    storageBucket: 'groc-b18e4.firebasestorage.app',
    iosClientId: '667875871369-vbpps4b2r6omsn7gv5plkhd8udhp63us.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryInventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhGEHV6eqB0-IsSWicNB9QCQlzrHmGoY0',
    appId: '1:667875871369:web:b4c9a83507468c09dad458',
    messagingSenderId: '667875871369',
    projectId: 'groc-b18e4',
    authDomain: 'groc-b18e4.firebaseapp.com',
    storageBucket: 'groc-b18e4.firebasestorage.app',
    measurementId: 'G-EN06NESHWF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB4Bd7X2nuhmDJ4G5U4I7bsqQhQzvK-oM',
    appId: '1:667875871369:ios:b1ee4ca6e67620ebdad458',
    messagingSenderId: '667875871369',
    projectId: 'groc-b18e4',
    storageBucket: 'groc-b18e4.firebasestorage.app',
    iosClientId: '667875871369-vbpps4b2r6omsn7gv5plkhd8udhp63us.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryInventoryApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1dbPk1Q-wzQS3foCxgE6H8UlLL_dwII',
    appId: '1:667875871369:android:fd4bf5d2e64a72bfdad458',
    messagingSenderId: '667875871369',
    projectId: 'groc-b18e4',
    storageBucket: 'groc-b18e4.firebasestorage.app',
  );

}